[versions]
#Gradle
gradle-plugin = "8.8.0"
#Jetpack
core = "1.15.0"
appcompat = "1.7.0"
room = "2.6.1"
activity = "1.10.0"
fragment = "1.8.5"
splash = "1.0.1"
#Google
material = "1.12.0"
gson = "2.11.0"
dagger = "2.55"
play-services-code-scanner = "16.1.0"
#Rx
rxjava = "3.1.10"
rxandroid = "3.0.2"
#Misc
desugar = "2.1.4"
qrgenerator = "1.0.1"
swipereveallayout = "1.4.0"
timber = "5.0.1"
#Testing
junit = "4.13.2"
core-testing = "2.2.0"
robolectric = "4.14.1"
mockito = "5.15.2"
junit-ext = "1.2.1"
espresso = "3.6.1"

[libraries]
#Jetpack
core = { group = "androidx.core", name = "core", version.ref = "core" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
activity = { module = "androidx.activity:activity", version.ref = "activity" }
fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splash" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-rxjava3 = { module = "androidx.room:room-rxjava3", version.ref = "room" }
#Google
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
material = { module = "com.google.android.material:material", version.ref = "material" }
play-services-code-scanner = { module = "com.google.android.gms:play-services-code-scanner", version.ref = "play-services-code-scanner" }
dagger-android = { module = "com.google.dagger:dagger-android", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
#Rx
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }
rxandroid = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxandroid" }
#Misc
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
swipereveallayout = { module = "com.github.hydrated:swipereveallayout", version.ref = "swipereveallayout" } #TODO Legacy library to be replaced
qrgenerator = { module = "com.github.androidmads:qrgenerator", version.ref = "qrgenerator" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
#Testing
junit = { module = "junit:junit", version.ref = "junit" }
core-testing = { module = "androidx.arch.core:core-testing", version.ref = "core-testing" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockito" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junit-ext" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "gradle-plugin" }
androidLibrary = { id = "com.android.library", version.ref = "gradle-plugin" }
